[[section-architecture-constraints]]
== Architecture Constraints


[role="arc42help"]
****
.Contents
Any requirement that constrains software architects in their freedom of design and implementation decisions or decision about the development process. These constraints sometimes go beyond individual systems and are valid for whole organizations and companies.

.Motivation
Architects should know exactly where they are free in their design decisions and where they must adhere to constraints.
Constraints must always be dealt with; they may be negotiable, though.

.Form
Simple tables of constraints with explanations.
If needed you can subdivide them into
technical constraints, organizational and political constraints and
conventions (e.g. programming or versioning guidelines, documentation or naming conventions)
****

=== Categories of Constraints

[role="arc42help"]
****
.Technical Constraints
Techincal constraints are fixed technical desing decisions that absolutely cannot be changed. 
Most often these are provided by stakeholders at the outset of the project. 
Sometimes a team may choose to create a constraint, 
perhaps to simplify the world in which they are working

Some of the technical constraints that the project currently has are the following

* The use of SOLID
* The use of the ReactJS framework
* Being able to make a functional project while maintaining the decentralized network system 
* Make good use of the POD system and its advantages
* Make sure that the files that store the routes are independent of the app
* Implementation of a web interface

.Business Constraints 
Business constraints are unchangeable business decisions that in some way restrict the software architecture design.  
Business constraints are similar to technical constraints in that they are decisions that cannot be changed, but rather than influencing structures directly through technology, the influence occurs indirectly through business decisions.

* Using SOLID and the resources that provides us 
* The usae of a GitHub repository in order to keep the development of the project in check and always available


****

