[[section-solution-strategy]]
== Solution Strategy


[role="arc42help"]
****
.Contents
The system consists in three main modules, a POD server preferably hosted in the machine of one of the developers, a Solid server also hosted in one of such machines and a Javascript client built with React that will provide the interface for the users to interact with the software solution.

As there are very different levels of skill in the development team in the various technologies that are going to be employed in the construction of the system, tasks are going to be divided among us in such a way that every developer has the chance to learn some of the basis of them in the implementation but the project's time to market meets the 3 month goal.

.Motivation
The system must be secure enough to prevent any kind of data loss, even in case of a security breach in the system.

.Form
Given that the developer in charge of the writing of this document is still learning the Javascript, Node, and React, this initial version of the document is not detailed, as will not be point 5.
****



Framework React +
This is a framework focused on JavaScript that will help us developing our app, facilitating the communication between interfaces and services. + 
See <<02_architecture_costraints.adoc>>

Asciidoctor +
This is the text processor we are using to write the documentation of our app.

Node.js +
It's a runtime environment that allows us execute JavaScript outside of a web browser and therefore it will help us to display the app.

Solid POD +
Solid pods are the way in which users will store their information in order to share and use it in the app.

Solid-auth-service +
This is a browser library that allows our app to connect securely to users pods and read and write data into them.

