[[section-solution-strategy]]
== Solution Strategy

////
[role="arc42help"]
****
.Contents
A short summary and explanation of the fundamental decisions and solution strategies, that shape the system's architecture. These include

* technology decisions
* decisions about the top-level decomposition of the system, e.g. usage of an architectural pattern or design pattern
* decisions on how to achieve key quality goals
* relevant organizational decisions, e.g. selecting a development process or delegating certain tasks to third parties.

.Motivation
These decisions form the cornerstones for your architecture. They are the basis for many other detailed decisions or implementation rules.

.Form
Keep the explanation of these key decisions short.

Motivate what you have decided and why you decided that way,
based upon your problem statement, the quality goals and key constraints.
Refer to details in the following sections.
****
////

Framework React +
This is a framework focused on JavaScript that will help us developing our app, facilitating the communication between interfaces and services. + 
See <<02_architecture_costraints.adoc>>

Asciidoctor +
This is the text processor we are using to write the documentation of our app.

Node.js +
It's a runtime environment that allows us execute JavaScript outside a web browser and therefore it will help us to display the app.

Solid POD +
Solid pods are the way in which users will store their information in order to share and use it in the app.

Solid-auth-service +
This is a browser library that allows our app to connect securely to users pods and read and write data into them.

