[[section-runtime-view]]
== Runtime View
This is not a definitive version. We will be adding more scenarios later

=== How does the application login work?

* Shows the login of the application and how the whole process works. 
* An user enters their credentials in the login interface. Then, that interface sends the request to the authenticator, which in turn validates the data on the SOLID server. From here, two situations can occur:
	** The first is that the session is correct and then loads the new graphical interface (that of the application) and then loads its own routes from its own POD.
	** The second option is that the login is invalid, which causes the graphical interface of the login to be loaded again with an error message.
* Notably,the SOLID server is different from the user's POD.


This is the sequence to generate the uml:

[plantuml,"Initial diagram",png]
----
title How does the login in the application work?

actor HIKER #red
participant UILogin #yellow
control Authentication #green
database SOLID #purple
database POD #pink
participant UIApplication #yellow

HIKER -> UILogin: Set credentials
UILogin -> Authentication: Login Request
Authentication -> SOLID: Validate credentials

alt Login Successful
	SOLID -> Authentication: Correct login
	Authentication --> UIApplication: Load Application
    POD->UIApplication: Load your own routes
	
else Login Failure
	SOLID -> Authentication: Invalid login
	Authentication --> UILogin: Load Login
	end

legend
|= Object |= Explain |= Color |
|HIKER | Is the users who will use the application.\nThe color that identifies the hikers is red |<back:#FF0000>   </back> |
|UIAplication and UILogin| They are the GUIs\n with which hikers can interact. All GUIs are yellow |<back:yellow>   </back> |
|Authentication service | It's a service.The color that identifies the services is green. |<back:green>   </back> |
|SOLID|The different colors of roses are to specify that one is\n the SOLID server (purple) and another your personal\n server (pink)|<back:pink>   </back> |
endlegend



----
=== Add route

* Show how a route is added to the application.
* The user wants to add a route. In the application there will be a button or something similar in which you can add a route. When everything requested to save the route has been added, there will be a service that validates that the route is correct. This service will try to save the route in your POD. From here, two situations can occur:
** That the route is saved successfully and you receive a message that it was saved correctly.
** Or that the route could not be saved and you receive an error message.

This is the sequence to generate the uml:

[plantuml,"Add route diagram",png]
----
title How do you add a route?



actor HIKER #red
participant UIApplication #yellow
control AddRouteService #green
database POD #pink

note right of Legend: 


HIKER -> UIApplication: ADD ROUTE
UIApplication -> AddRouteService: AddRouteInYourPOD()
AddRouteService -> POD: Save route in your POD

alt correct
	POD -> AddRouteService: Route saved
	AddRouteService --> UIApplication: Successful message

else incorrect
	POD -> AddRouteService: Route could't be saved
	AddRouteService --> UIApplication: Failure message
	end

legend
|= Object |= Explain |= Color |
|HIKER | Is the users who will use the application.\nThe color that identifies the hikers is red |<back:#FF0000>    </back> |
|UIAplication | They are the GUIs\n with which hikers can interact. All GUIs are yellow |<back:yellow>     </back> |
|AddRoute service | It's a service that allows you to upload routes to your pod.The color that identifies the services is green. |<back:green>    </back> |
|SOLID|Pink color identify your personal\n server (pink)|<back:pink>    </back> |
endlegend
----


=== Map view with routes ===

* The user clicks on the "View map" button and then clicks on the route of his pod that he wants to see on the map.
* Then the service will take care of asking the POD for that route and show it on the map, which here is divided into two options:
** You have chosen a route and it has been possible to download the POD, which will be shown on the map
** You have chosen a route and it could not be downloaded from the POD, which will show an error message

This is the sequence to generate the uml:

[plantuml,"View Map",png]
----
title View a map with routes



actor USER #red
participant UI #yellow
control DataService #green
database POD #pink

USER-> UI : Click button "Ver Mapa"
USER -> UI: Select route
UI -> DataService: getRoute()
DataService -> POD: Get Route of POD

alt successful
	POD -> DataService: Route
	DataService --> UI: Successful notification

else failure
	POD -> DataService: No Route
	DataService --> UI: Error notification
	end

legend
|= Object |= Explain |= Color |
|HIKER | Is the users who will use the application.\nThe color that identifies the hikers is red |<back:#FF0000>    </back> |
|UIAplication | They are the GUIs\n with which hikers can interact. All GUIs are yellow |<back:yellow>     </back> |
|AddRoute service | It's a service that allows you to view routes in the map.The color that identifies the services is green. |<back:green>    </back> |
|SOLID|Pink color identify your personal\n server (pink)|<back:pink>    </back> |
endlegend
----
=== Share routes ===

* The user clicks on the "Share routes" button and And you can click on the route you want to share.
* Then you can select the friend with whom you want to share that route and the service will take care of getting that route from your POD and send the route to your friend's POD:
** You have chosen a route and it has been possible to download the POD and it has been successfully sent to your friend
** You have chosen a route and it could not be sended to your friend's POD, which will show an error message

** If the route has been received correctly notify your friend that they have a new shared route

**  If the route could not be received, a notification will be sent to your friend that the route could not be received.

This is the sequence to generate the uml:

[plantuml,"Share routes",png]
----
title Share routes with your friends



actor USER #red
participant UI #yellow
control DataService #green
database POD #pink
participant FRIEND_UI #yellow
database FRIEND_POD #pink

USER -> UI: SHARE Route
UI -> DataService: shareRoute(friend)
DataService -> POD: Get Route
DataService -> FRIEND_POD: Send Route

alt successful
	POD -> DataService: Route sended
	DataService --> UI: Successful notification

else failure
	POD -> DataService: Route not sended
	DataService --> UI: Failure notification
	end



alt successful
	FRIEND_POD -> DataService: Route received
	DataService --> FRIEND_UI: Successful notification

else failure
	FRIEND_POD -> DataService: Route not received
	DataService --> FRIEND_UI: Failure notification
	end

legend
|= Object |= Explain |= Color |
|HIKER | Is the users who will use the application.\nThe color that identifies the hikers is red |<back:#FF0000>    </back> |
|UIAplication | They are the GUIs\n with which hikers can interact. All GUIs are yellow |<back:yellow>     </back> |
|AddRoute service | It's a service that allows you to view routes in the map.The color that identifies the services is green. |<back:green>    </back> |
|SOLID|Pink color identify your personal\n server (pink)|<back:pink>    </back> |
endlegend
----

