[[section-runtime-view]]
== Runtime View


[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...

****
This part will be focused to see how the application is structured and iterated when users take a certain action. The scenarios will go in order in which the application runs

=== How does the application login work?


* Shows the login of the application and how the whole process works
* _<insert description of the notable aspects of the interactions between the
building block instances depicted in this diagram.>_

This is the sequence to generate the uml:

[plantuml,"Sequence diagram",png]
----
title How does the login in the application work?



actor USER #red
participant UILogin #blue
control Authentication #green
database SOLID #purple
database POD #pink
participant UIApplication #blue


USER -> UILogin: Set credentials
UILogin -> Authentication: Login Request
Authentication -> SOLID: Validate credentials

alt Login Successful
	SOLID -> Authentication: Correct login
	Authentication --> UIApplication: Load Application
    POD->UIApplication: Load your own routes

else Login Failure
	SOLID -> Authentication: Invalid login
	Authentication --> UILogin: Load Login
	end


----
=== <Runtime Scenario 2>

=== ...

=== <Runtime Scenario n>
