[[section-design-decisions]]
== Design Decisions
Some design decisions are also involved in point 4. +
See <<04_solution_strategy.adoc>>. Here are some of the most important:
[%header,cols=5*] 
|===
|Section
|Decision
|Date
|Pros
|Cons

|Programming language
|Javascript
|11-02-2020
|Async task
|Better handling of language

|Design Pattern
|MVC (Model View Controller)
|18-02-2020
|Easy to implement and efficient
|Simple

|IDE
|Visual Studio Code
|20-02-2020
|Easy to use and very complete.Ability to add extensions
|Some cons are solved with extensions

|Testing
|Unit Tests
|16-03-2020
|Tests incorporated into the React skeleton
|Does not perform exhaustive tests, you have to do them

|Map
|Leaflet
|10-03-2020
|Javascript library that shows us the map and allows us to put points. It's free.
|Other competitive libraries

|Storage
|JSON / RDF
|27-03-2020
|Most used language and persistence
|Just support one

|Friends
|query-LDflex
|28-04-2020
|Solid ecosystem
|A little limited in several ways

|===

////
[role="arc42help"]
****
.Contents
Important, expensive, large scale or risky architecture decisions including rationals.
With "decisions" we mean selecting one alternative based on given criteria.

Please use your judgement to decide whether an architectural decision should be documented
here in this central section or whether you better document it locally
(e.g. within the white box template of one building block).

Avoid redundancy. Refer to section 4, where you already captured the most important decisions of your architecture.

.Motivation
Stakeholders of your system should be able to comprehend and retrace your decisions.

.Form
Various options:
-
* List or table, ordered by importance and consequences or:
* more detailed in form of separate sections per decision
* ADR (architecture decision record) for every important decision
****
////

Routes sharing is unidirectional. +
It means that an user doesn't have to share his routes to another one once the second one has shared his own routes.

Syntax of the storage. +
Choosing the language in which to write the routes is a very difficult decision. A chat was enabled to discuss it (https://github.com/Arquisoft/viadeSpec[viadeSpec]), but there was no consensus. So we have decided to support JSON and different parsers for other types of files.


