[[section-technical-risks]]
== Risks and Technical Debts

////
[role="arc42help"]
****
.Contents
A list of identified technical risks or technical debts, ordered by priority

.Motivation
“Risk management is project management for grown-ups” (Tim Lister, Atlantic Systems Guild.) 

This should be your motto for systematic detection and evaluation of risks and technical debts in the architecture, which will be needed by management stakeholders (e.g. project managers, product owners) as part of the overall risk analysis and measurement planning.

.Form
List of risks and/or technical debts, probably including suggested measures to minimize, mitigate or avoid risks or reduce technical debts.
****
////
The main risks we have identified in the implmentation of this application are the following ones:
[%header,cols=2*]
|===
| Risk | Solution

|Adaptation between members of the team
|We are 5 people who have worked together rarely or none and, although we know that this is what our future probably holds to us, the lack of communication or rapport between all of us is still a risk.

|Short term reviews
|We have very little time to develop the first version of our application (3 weeks) and if we don't organize well it can be a disaster.

|Support more route file formats
|In the absence of a decision to allow interoperability. The decision was to format one of the most widely used in the world for data transfer, JSON. We leave as a possibility to expand some parsers to allow more types of files

|===